module.exports = function (sequelize, DataTypes){
    return sequelize.define('score', {
       golf_course:DataTypes.STRING,
       user_id: DataTypes.INTEGER,
       date: DataTypes.DATEONLY,
       hole1: DataTypes.INTEGER,
       hole2: DataTypes.INTEGER,
       hole3: DataTypes.INTEGER,
       hole4: DataTypes.INTEGER,
       hole5: DataTypes.INTEGER,
       hole6: DataTypes.INTEGER,
       hole7: DataTypes.INTEGER,
       hole8: DataTypes.INTEGER,
       hole9: DataTypes.INTEGER,
       hole10: DataTypes.INTEGER,
       hole11: DataTypes.INTEGER,
       hole12: DataTypes.INTEGER,
       hole13: DataTypes.INTEGER,
       hole14: DataTypes.INTEGER,
       hole15: DataTypes.INTEGER,
       hole16: DataTypes.INTEGER,
       hole17: DataTypes.INTEGER,
       hole18: DataTypes.INTEGER,
       front9: DataTypes.INTEGER,
       back9: DataTypes.INTEGER,
       total: DataTypes.INTEGER,
       rating: DataTypes.INTEGER,
       notes: DataTypes.STRING,
    });
};